export const CATEGORY_SEED = [
  { id: 'all', name: 'All Menu' },
  { id: 'coffee', name: 'Coffee' },
  { id: 'bread', name: 'Breads' },
  { id: 'cake', name: 'Cakes' },
  { id: 'donut', name: 'Donuts' },
  { id: 'pastry', name: 'Pastries' },
  { id: 'sandwich', name: 'Sandwich' },
]

export const PRODUCT_SEED = [
  {
    id: 'm01',
    name: 'Beef Crowich',
    category: 'sandwich',
    label: 'Sandwich',
    basePrice: 5.5,
    image:
      'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Toasted bun, juicy beef patty, and fresh greens.',
    customizable: 1,
    options: {
      size: [
        { name: 'Regular', price: 0 },
        { name: 'Large', price: 1 },
      ],
      extras: [
        { name: 'No Extras', price: 0 },
        { name: 'Cheese', price: 0.75 },
        { name: 'Bacon', price: 1.2 },
      ],
    },
  },
  {
    id: 'm02',
    name: 'Buttermelt Croissant',
    category: 'pastry',
    label: 'Pastry',
    basePrice: 4,
    image:
      'https://images.unsplash.com/photo-1555507036-ab794f57593b?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Premium butter croissant with crispy crust and soft inside.',
    customizable: 1,
    options: {
      size: [{ name: 'Single', price: 0 }],
      extras: [
        { name: 'No Extras', price: 0 },
        { name: 'Chocolate Dip', price: 0.8 },
      ],
    },
  },
  {
    id: 'm03',
    name: 'Cereal Cream Donut',
    category: 'donut',
    label: 'Donut',
    basePrice: 2.45,
    image:
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Fluffy donut finished with cereal cream glaze.',
    customizable: 0,
    options: null,
  },
  {
    id: 'm04',
    name: 'Cheesy Cheesecake',
    category: 'cake',
    label: 'Cake',
    basePrice: 3.75,
    image:
      'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Rich and creamy cheesecake slice with buttery crumb.',
    customizable: 0,
    options: null,
  },
  {
    id: 'm05',
    name: 'Cheezy Sourdough',
    category: 'bread',
    label: 'Bread',
    basePrice: 4.5,
    image:
      'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Fresh sourdough loaf with melted cheddar center.',
    customizable: 0,
    options: null,
  },
  {
    id: 'm06',
    name: 'Egg Tart',
    category: 'pastry',
    label: 'Tart',
    basePrice: 3.25,
    image:
      'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Silky baked custard in a flaky shell.',
    customizable: 0,
    options: null,
  },
  {
    id: 'm07',
    name: 'Grains Pan Bread',
    category: 'bread',
    label: 'Bread',
    basePrice: 4.5,
    image:
      'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Multi-grain baked bread, soft center and crispy top.',
    customizable: 0,
    options: null,
  },
  {
    id: 'm08',
    name: 'Spinchoco Roll',
    category: 'pastry',
    label: 'Pastry',
    basePrice: 4,
    image:
      'https://images.unsplash.com/photo-1541782814456-0d7f8f4b31ea?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Rolled pastry filled with dark chocolate cream.',
    customizable: 0,
    options: null,
  },
  {
    id: 'm09',
    name: 'Sliced Black Forest',
    category: 'cake',
    label: 'Cake',
    basePrice: 5,
    image:
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Moist chocolate layers with whipped cream.',
    customizable: 0,
    options: null,
  },
  {
    id: 'm10',
    name: 'Solo Floss Bread',
    category: 'bread',
    label: 'Bread',
    basePrice: 4.5,
    image:
      'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Soft bun topped with savory floss.',
    customizable: 0,
    options: null,
  },
  {
    id: 'm11',
    name: 'Espresso Shot',
    category: 'coffee',
    label: 'Coffee',
    basePrice: 2.5,
    image:
      'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Intense single-origin espresso with rich crema.',
    customizable: 1,
    options: {
      size: [
        { name: 'Single', price: 0 },
        { name: 'Double', price: 1.25 },
      ],
      extras: [
        { name: 'No Extras', price: 0 },
        { name: 'Extra Shot', price: 1 },
      ],
    },
  },
  {
    id: 'm12',
    name: 'Americano',
    category: 'coffee',
    label: 'Coffee',
    basePrice: 3.25,
    image:
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Smooth espresso diluted with hot water for a clean finish.',
    customizable: 1,
    options: {
      size: [
        { name: 'Regular', price: 0 },
        { name: 'Large', price: 0.75 },
      ],
      extras: [
        { name: 'No Extras', price: 0 },
        { name: 'Extra Shot', price: 1 },
      ],
    },
  },
  {
    id: 'm13',
    name: 'Cappuccino',
    category: 'coffee',
    label: 'Coffee',
    basePrice: 3.95,
    image:
      'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Balanced espresso with steamed milk and thick foam.',
    customizable: 1,
    options: {
      size: [
        { name: 'Regular', price: 0 },
        { name: 'Large', price: 0.85 },
      ],
      extras: [
        { name: 'No Extras', price: 0 },
        { name: 'Oat Milk', price: 0.6 },
        { name: 'Extra Shot', price: 1 },
      ],
    },
  },
  {
    id: 'm14',
    name: 'Latte',
    category: 'coffee',
    label: 'Coffee',
    basePrice: 4.2,
    image:
      'https://images.unsplash.com/photo-1521302200778-33500795e128?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Creamy espresso latte with silky steamed milk.',
    customizable: 1,
    options: {
      size: [
        { name: 'Regular', price: 0 },
        { name: 'Large', price: 0.9 },
      ],
      extras: [
        { name: 'No Extras', price: 0 },
        { name: 'Vanilla Syrup', price: 0.5 },
        { name: 'Caramel Syrup', price: 0.5 },
      ],
    },
  },
  {
    id: 'm15',
    name: 'Iced Mocha',
    category: 'coffee',
    label: 'Coffee',
    basePrice: 4.75,
    image:
      'https://images.unsplash.com/photo-1578314675249-a6910f80cc9d?auto=format&fit=crop&q=80&w=480&h=320',
    description: 'Chilled mocha blend with espresso, cocoa, and milk.',
    customizable: 1,
    options: {
      size: [
        { name: 'Regular', price: 0 },
        { name: 'Large', price: 0.95 },
      ],
      extras: [
        { name: 'No Extras', price: 0 },
        { name: 'Whipped Cream', price: 0.6 },
        { name: 'Extra Shot', price: 1 },
      ],
    },
  },
]

export const TABLE_SEED = [
  { id: 'T-01', groupTitle: '2 Persons Table', guest: 'Sharon', pax: 2, time: '09:00 AM', status: 'served' },
  { id: 'T-02', groupTitle: '2 Persons Table', guest: '0 Guest', pax: 0, time: '--:--', status: 'available' },
  { id: 'T-03', groupTitle: '2 Persons Table', guest: 'Billie', pax: 2, time: '09:00 AM', status: 'served' },
  { id: 'T-04', groupTitle: '2 Persons Table', guest: 'Mike', pax: 1, time: '09:00 AM', status: 'served' },
  { id: 'T-05', groupTitle: '2 Persons Table', guest: '0 Guest', pax: 0, time: '--:--', status: 'available' },
  { id: 'T-06', groupTitle: '2 Persons Table', guest: '0 Guest', pax: 0, time: '--:--', status: 'available' },
  { id: 'T-07', groupTitle: '4 Persons', guest: '0 Guest', pax: 0, time: '--:--', status: 'available' },
  { id: 'T-08', groupTitle: '4 Persons', guest: 'Hyacinth', pax: 3, time: '01:00 PM', status: 'reserved' },
  { id: 'T-09', groupTitle: '4 Persons', guest: '0 Guest', pax: 0, time: '--:--', status: 'available' },
  { id: 'T-10', groupTitle: '4 Persons', guest: 'Justin', pax: 4, time: '09:30 AM', status: 'served' },
  { id: 'T-11', groupTitle: 'Max 12 Persons', guest: '0 Guest', pax: 0, time: '--:--', status: 'available' },
  { id: 'T-12', groupTitle: 'Max 12 Persons', guest: 'Clark', pax: 5, time: '11:00 AM', status: 'served' },
  { id: 'T-13', groupTitle: 'Max 12 Persons', guest: 'Meera', pax: 10, time: '12:00 PM', status: 'reserved' },
  { id: 'T-14', groupTitle: 'Max 12 Persons', guest: '0 Guest', pax: 0, time: '--:--', status: 'available' },
  { id: 'T-15', groupTitle: 'Max 12 Persons', guest: '0 Guest', pax: 0, time: '--:--', status: 'available' },
  { id: 'T-16', groupTitle: 'Max 12 Persons', guest: 'Wendy', pax: 12, time: '12:30 PM', status: 'reserved' },
]

export const ORDER_SEED = [
  {
    orderNumber: '#006',
    customerName: 'Francois',
    tableName: 'Table 06',
    orderType: 'Dine In',
    status: 'Active',
    paymentStatus: 'Unpaid',
    kitchenStatus: 'On Kitchen Hand',
    createdAt: '2024-05-29T09:15:00.000Z',
    subtotal: 20,
    tax: 2,
    total: 22,
    items: [
      { productId: 'm01', quantity: 2, unitPrice: 5.5, totalPrice: 11 },
      { productId: 'm05', quantity: 2, unitPrice: 4.5, totalPrice: 9 },
    ],
  },
  {
    orderNumber: '#005',
    customerName: 'Eloise',
    tableName: 'Table 05',
    orderType: 'Dine In',
    status: 'Closed',
    paymentStatus: 'Paid',
    kitchenStatus: 'All Done',
    createdAt: '2024-05-29T09:00:00.000Z',
    subtotal: 19.35,
    tax: 1.94,
    total: 21.29,
    items: [
      { productId: 'm01', quantity: 1, unitPrice: 5.5, totalPrice: 5.5 },
      { productId: 'm09', quantity: 1, unitPrice: 5, totalPrice: 5 },
      { productId: 'm10', quantity: 2, unitPrice: 4.425, totalPrice: 8.85 },
    ],
  },
  {
    orderNumber: '#004',
    customerName: 'Mike',
    tableName: 'Table 04',
    orderType: 'Dine In',
    status: 'Done',
    paymentStatus: 'Paid',
    kitchenStatus: 'All Done',
    createdAt: '2024-05-25T08:35:00.000Z',
    subtotal: 22.1,
    tax: 2.21,
    total: 24.31,
    items: [
      { productId: 'm02', quantity: 2, unitPrice: 4, totalPrice: 8 },
      { productId: 'm09', quantity: 1, unitPrice: 5, totalPrice: 5 },
      { productId: 'm10', quantity: 2, unitPrice: 4.55, totalPrice: 9.1 },
    ],
  },
  {
    orderNumber: '#003',
    customerName: 'Billie',
    tableName: 'Table 03',
    orderType: 'Take Away',
    status: 'Done',
    paymentStatus: 'Paid',
    kitchenStatus: 'All Done',
    createdAt: '2024-05-25T08:17:00.000Z',
    subtotal: 12.5,
    tax: 1.25,
    total: 13.75,
    items: [
      { productId: 'm02', quantity: 1, unitPrice: 4, totalPrice: 4 },
      { productId: 'm03', quantity: 1, unitPrice: 2.45, totalPrice: 2.45 },
      { productId: 'm08', quantity: 1, unitPrice: 4, totalPrice: 4 },
      { productId: 'm06', quantity: 1, unitPrice: 2.05, totalPrice: 2.05 },
    ],
  },
  {
    orderNumber: '#002',
    customerName: 'Eliza',
    tableName: 'Table 01',
    orderType: 'Dine In',
    status: 'Canceled',
    paymentStatus: 'Unpaid',
    kitchenStatus: 'Canceled',
    createdAt: '2024-05-25T08:42:00.000Z',
    subtotal: 12.25,
    tax: 1.22,
    total: 13.47,
    items: [{ productId: 'm04', quantity: 2, unitPrice: 3.75, totalPrice: 7.5 }],
  },
]
